// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: flows.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertFlow = `-- name: InsertFlow :one
INSERT INTO flows (
  name, status, container_id
)
VALUES (
  $1, $2, $3
)
RETURNING id, created_at, updated_at, deleted_at, name, status, container_id
`

type InsertFlowParams struct {
	Name        pgtype.Text
	Status      pgtype.Text
	ContainerID pgtype.Int8
}

func (q *Queries) InsertFlow(ctx context.Context, arg InsertFlowParams) (Flow, error) {
	row := q.db.QueryRow(ctx, insertFlow, arg.Name, arg.Status, arg.ContainerID)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Status,
		&i.ContainerID,
	)
	return i, err
}
